security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
    org.springframework.retry: DEBUG
      
spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: route
      
fortune-service:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
